### ISSUE TITLE
More Animals 3.0

### ISSUE THREAD

**Issue by Entoarox** [StardewModders/mod-translations#10]
**[More Animals](https://www.nexusmods.com/stardewvalley/mods/2274)** lets you to get more pets, and optionally randomises the appearance of your farm animals based on the sprites you download.

## Requested translations
See [default text](https://github.com/Entoarox/StardewMods/blob/master/MoreAnimals/i18n/default.json) and [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

language | translations | status
-------- | ------------ | ------
~~Chinese~~ | ~~[zh.json](https://github.com/Entoarox/StardewMods/blob/master/MoreAnimals/i18n/zh.json)~~ | added (thanks to @binxhlin!)
French | ~~[fr.json](https://github.com/Entoarox/StardewMods/blob/master/MoreAnimals/i18n/fr.json)~~ | [added](https://github.com/Entoarox/StardewMods/pull/75) (thanks to @ManekiNeko-89!).
German | | missing
Hungarian | | missing
~~Italian~~ | ~~[it.json](https://github.com/Entoarox/StardewMods/blob/master/MoreAnimals/i18n/it.json)~~ | [added](https://github.com/Entoarox/StardewMods/pull/66) (thanks to @sfal!).
Japanese | | missing
~~Korean~~ | ~~[ko.json](https://github.com/Entoarox/StardewMods/blob/master/MoreAnimals/i18n/ko.json)~~ | [added](https://github.com/Entoarox/StardewMods/pull/63) (thanks to @S2SKY!).
~~Portuguese~~ | ~~[pt.json](https://github.com/Entoarox/StardewMods/blob/master/MoreAnimals/i18n/pt.json)~~ | [added](https://github.com/Entoarox/StardewMods/pull/64) (thanks to @kelvindules!).
~~Russian~~ | ~~[ru.json](https://github.com/Entoarox/StardewMods/blob/master/MoreAnimals/i18n/ru.json)~~ | [added](https://github.com/Entoarox/StardewMods/pull/78) (thanks to @TheOzonO3!).
~~Spanish~~ | ~~[es.json](https://github.com/Entoarox/StardewMods/blob/master/MoreAnimals/i18n/es.json)~~ | added (thanks to @manuqp!).
Turkish | | missing

Here's where the translations appear:
* **TODO**

## Credit
**TODO**

## See also
* [source code](https://github.com/Entoarox/StardewMods)

**Comment by Pathoschild** [comment]
@Entoarox I expanded your description per [Modding:Translations#Request translations](https://stardewvalleywiki.com/Modding:Translations#Request_translations). Can you fill in the **TODO**s (see [this ticket for an example](https://github.com/StardewModders/mod-translations/issues/9))?

**Comment by ManekiNeko-89** [comment]
{
  "EmptyBox": "Juste une boîte vide.",
  "AdoptMessage": "Oh non, on dirait que quelqu'un a abandonné un pauvre {{petType}} ici ! Peut-être devriez-vous payer Marnie {{adoptionPrice}} po pour qu'elle lui fasse un bilan de santé pour pouvoir l'adopter ?",
  "AdoptNoGold": "Malheureusement, je n'ai pas les {{adoptionPrice}} po nécessaires pour le faire.",
  "AdoptYes": "Oui, je devrais vraiment adopter ce pauvre animal !",
  "AdoptNo": "Non, je n'ai pas la place pour l'accueillir.",
  "ChooseName": "Choisissez un nom",
  "Adopted": "Marnie amènera {{petName}} chez vous une fois qu'elle aura fait leur bilan de santé."
}

**Comment by manuqp** [comment]
Spanish translation :)

{
  "EmptyBox": "Solo es una caja vacía.",
  "AdoptMessage": "¡Oh cielos, parece que alguien ha abandonado un ejemplar de {{petType}}! Quizás pueda pagarle a Marnie {{adoptionPrice}}G para que le haga un chequeo y así poder adoptarlo.",
  "AdoptNoGold": "Desgraciadamente, no tengo los {{adoptionPrice}}G para hacerlo.",
  "AdoptYes": "¡Sí, debería adoptar al pobre animal!",
  "AdoptNo": "No, no tengo espacio para acogerlo.",
  "ChooseName": "Elige un nombre",
  "Adopted": "Marnie llevará a {{petName}} a tu casa una vez le haya hecho el chequeo."
}

**Comment by binxhlin** [comment]
Hello
I create "zh.txt" file and you just rename ".txt" to ".json"
[zh.txt](https://github.com/StardewModders/mod-translations/files/3047439/zh.txt)

**Comment by Pathoschild** [comment]
@Entoarox You have a pending translation above; could you add it to the repository?

**Comment by Entoarox** [comment]
@Pathoschild I already added it on my end, guess it didnt sync to github >_<

**Comment by Pathoschild** [comment]
@Entoarox Any progress on syncing it to GitHub?

**Comment by Pathoschild** [comment]
@Entoarox I closed this ticket due to non-response. Feel free to create a new ticket when you have time to handle translations!
