### ISSUE TITLE
Chests Anywhere 1.17.2

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#11]
**[Chests Anywhere](https://www.nexusmods.com/stardewvalley/mods/518)** lets you access your chests, fridge, shipping bin, and Junimo huts from anywhere and organise them your way. Transfer items without having to run around, from the comfort of your bed to the deepest mine level.

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[Chinese](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/zh.json)~ (updated thanks to @binxhlin!)
- [x] ~[French](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/fr.json)~ (updated thanks to @Avisend!)
- [x] ~[German](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/de.json)~ (updated thanks to @Firevulture!)
- [ ] Hungarian (missing)
- [x] ~[Italian](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/it.json)~ (added thanks to @LeecanIt!)
- [x] ~[Japanese](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/ja.json)~ ([updated](https://github.com/Pathoschild/StardewMods/pull/431) thanks to @shirutan!)
- [x] ~[Korean](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/ko.json)~ ([updated](https://github.com/Pathoschild/StardewMods/pull/399) thanks to @YSRyeol!)
- [x] ~[Portuguese](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/pt.json)~ (updated (thanks to @SolidJade!))
- [x] ~[Russian](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/ru.json)~ ([updated](https://github.com/Pathoschild/StardewMods/pull/395) thanks to @TheOzonO3!)
- [x] ~[Spanish](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/es.json)~ ([updated](https://github.com/Pathoschild/StardewMods/pull/408) thanks to @Yllelder!)
- [x] ~[Turkish](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/tr.json)~ (added thanks to @cilekli-link!)

## Where translations appear in-game
The mod adds new options to the chest UI:
* After opening a chest, click the top-left dropdown to see default names for chests and machines:
  > ![](https://user-images.githubusercontent.com/230581/54803190-dbc33000-4c44-11e9-8dd7-26537637ee80.png)
* Click the edit icon to view the chest options:
   > ![](https://user-images.githubusercontent.com/230581/54803175-ccdc7d80-4c44-11e9-8ea4-87414ace02b2.png)
   > ![](https://user-images.githubusercontent.com/230581/54803067-59d30700-4c44-11e9-93c1-5462004f1b24.png)

Errors are shown as popup notifications in the bottom-left corner:  
  > ![](https://user-images.githubusercontent.com/230581/50676019-d8ae9100-0fbf-11e9-8dc8-d8b36673ccb8.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/ChestsAnywhere)

**Comment by binxhlin** [comment]
I update chinese translation.
[zh.txt](https://github.com/StardewModders/mod-translations/files/3051273/zh.txt)

**Comment by Pathoschild** [comment]
Thanks!

**Comment by Firevulture** [comment]
[de.json.txt](https://github.com/StardewModders/mod-translations/files/3101267/de.json.txt)

Translated the todos for the German translation

**Comment by Pathoschild** [comment]
@Firevulture Thanks! I added it to the next Chests Anywhere update.

**Comment by SolidJade** [comment]
[pt.txt](https://github.com/StardewModders/mod-translations/files/3283457/pt.txt)
Translated the TODOS and fixed the Auto-Grabber translation to match the game.

**Comment by Pathoschild** [comment]
@SolidJade To clarify, should `default-category.unowned-cabin` really say "Cabana (empty)"? The text in parentheses seems untranslated.

**Comment by SolidJade** [comment]
@Pathoschild Oops, you're right. I edited it on the .json archive and didn't replaced the .txt version.
But here it is. Sorry about this.
[pt.txt](https://github.com/StardewModders/mod-translations/files/3284230/pt.txt)
If you notice another error, or something I left behind, please let me know. It's actually the first time i do this xD But I'm sure this won't happen again.

**Comment by Pathoschild** [comment]
@SolidJade Added in the next Chests Anywhere update. Thanks for the help!

**Comment by cilekli-link** [comment]
Here's the Turkish translation:
[tr.txt](https://github.com/StardewModders/mod-translations/files/3314307/tr.txt)

**Comment by Pathoschild** [comment]
@cilekli-link Thanks! Added in the upcoming Chests Anywhere release.

**Comment by xCarloC** [comment]
Hi, this is the italian translation:
[it.txt](https://github.com/StardewModders/mod-translations/files/4174664/it.txt)

**Comment by mael-belval** [comment]
French seems ok on develop, I think you should pass it to done

**Comment by Pathoschild** [comment]
@xCarloC Sorry! Looks like someone already translated Italian, but I didn't update it here. Can you combine your translations with [the existing ones](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/it.json)?

@mael-belval Thanks!

**Comment by Pathoschild** [comment]
Chests Anywhere 1.17.3 updated with new translations; closed in favor of #28.
