### ISSUE TITLE
Data Layers 1.6.2

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#14]
**[Data Layers](https://www.nexusmods.com/stardewvalley/mods/1691)** overlays the world with visual data like bee/Junimo/scarecrow/sprinkler coverage, hidden paths and warps, and more.

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

language | translations | status
-------- | ------------ | ------
~~Chinese~~ | ~~[zh.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/zh.json)~~ | updated (thanks to @binxhlin!)
~~French~~ | ~~[fr.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/fr.json)~~ | updated (thanks to @Skirmsiher!)
~~German~~ | ~~[de.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/de.json)~~ | updated (thanks to @Firevulture!)
Hungarian | | missing
Italian | | missing
~~Japanese~~ | ~~[ja.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/ja.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/432) (thanks to @shirutan!)
~~Korean~~ | ~~[ko.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/ko.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/400) (thanks to @YSRyeol!)
~~Portuguese~~ | ~~[pt.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/pt.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/445) (thanks to @shiro2579!)
~~Russian~~ | ~~[ru.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/ru.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/396) (thanks to TheOzonO3!)
~~Spanish~~ | ~~[es.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/es.json)~~ | updated (thanks to @PlussRolf!)
Turkish | | missing

## Where translations appear in-game
Press `F2` in-game to show the data layer menu, then press `left CTRL` or `right CTRL` to cycle through the available overlays. See [the readme](https://github.com/Pathoschild/StardewMods/tree/develop/DataLayers#use) for an example of each overlay.

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/DataLayers)

**Comment by binxhlin** [comment]
Hello
I update your "zh.json" file and you just rename ".txt" to ".json"
[zh.txt](https://github.com/StardewModders/mod-translations/files/3046358/zh.txt)

**Comment by Pathoschild** [comment]
@binxhlin Thanks! I added your updates, but you're missing some of the new fields. See the `// TODO` sections in the new [zh.json](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/zh.json) if you want to translate those too.

**Comment by binxhlin** [comment]
I update the new [zh.txt](https://github.com/StardewModders/mod-translations/files/3051102/zh.txt) here.
By the way,is the "Occupied" means you can do it but something need to move?(like a chest)
But "Buildable" in your mod it is red color.

**Comment by Pathoschild** [comment]
Thanks! Yes, that's what it means by 'occupied'.

Buildable looks green for me. It's an overlay though, so it might look less green if something behind it is yellow or red:
> ![](https://user-images.githubusercontent.com/230581/55678444-ed086f80-58c7-11e9-94ba-4fa8a322892e.png)

**Comment by Firevulture** [comment]
[de.json.txt](https://github.com/StardewModders/mod-translations/files/3101292/de.json.txt)

German translation update

**Comment by Pathoschild** [comment]
Thanks! Added to the next Data Layers update.

**Comment by SkirOwen** [comment]
Hello,
I update the fr.json
[fr.json.txt](https://github.com/StardewModders/mod-translations/files/3381063/fr.json.txt)

**Comment by Pathoschild** [comment]
@Skirmsiher Thanks for the help! I added it to the next update.

**Comment by PlussRolf** [comment]
Finished the es.json
[es.json.txt](https://github.com/StardewModders/mod-translations/files/3965898/es.json.txt)

**Comment by Pathoschild** [comment]
@PlussRolf Thanks a lot! Added to the next Data Layers update.

**Comment by Pathoschild** [comment]
Data Layers updated with new translations; closed in favor of #22.
