### ISSUE TITLE
Lookup Anything 1.22.1

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#15]
**[Lookup Anything](https://www.nexusmods.com/stardewvalley/mods/541)** shows live info about whatever's under your cursor when you press F1. Learn a villager's favourite gifts, when a crop will be ready to harvest, how long a fence will last, why your farm animals are unhappy, and more. 

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/default.json) and [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

language | translations | status
-------- | ------------ | ------
Chinese | [zh.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/zh.json) | incomplete (see lines marked `// TODO`)
French | [fr.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/fr.json) | incomplete (see lines marked `// TODO`)
~~German~~ | ~~[de.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/de.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/438) (thanks to @jahangmar!)
Hungarian | | missing
Italian | | missing
~~Japanese~~ | ~~[ja.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ja.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/461) (thanks to pomepome!)
Korean | [ko.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ko.json) | incomplete (see lines marked `// TODO`)
~~Portuguese~~ | ~~[pt.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/pt.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/447) (thanks to @shiro2579!)
~~Russian~~ | ~~[ru.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ru.json)~~ | updated (thanks to @FixThisPlz!)
~~Spanish~~ | ~~[es.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/es.json)~~ | updated (thanks to @PlussRolf!)
Turkish | | missing

See [the readme](https://github.com/Pathoschild/StardewMods/tree/develop/LookupAnything#showcase) for examples showing where the translations appear. For example:

* `item.*` appear when you lookup items:  
  > ![common mushroom](https://user-images.githubusercontent.com/230581/50718635-aa808e00-105f-11e9-9c9c-87372c1b3fc9.png)

* `building.*` and `type.building` appear when you lookup different buildings:  
  > ![barn](https://user-images.githubusercontent.com/230581/50718529-8bcdc780-105e-11e9-9aae-e44fe5ea3573.png)  

* `friendship-status.*` is shown when you lookup an NPC:  
  > ![](https://user-images.githubusercontent.com/230581/50718706-5f1aaf80-1060-11e9-8b35-90e9b9d4c85f.png)

* `player.*` appear when you lookup yourself, either from the load screen or in-game:  
  > ![](https://user-images.githubusercontent.com/230581/50718664-fc291880-105f-11e9-8c64-c1218bb7bb8b.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/LookupAnything)

**Comment by kionell** [comment]
Hello! I'm trying to help with russian translations of some mods. With this, i have fixed some typo and mistakes of previous translation. Also, all lacking parts were translated. Just rename it back to json :)

[ru.txt](https://github.com/StardewModders/mod-translations/files/3356832/ru.txt)

**Comment by Pathoschild** [comment]
@FixThisPlz Thanks for the help! Added to the next Lookup Anything update.

**Comment by PlussRolf** [comment]
Finished up the Spanish translation, cleaned up a bit and left some comments on changes or why didn't translate it (Just Slimes).

[es.json.txt](https://github.com/StardewModders/mod-translations/files/3965816/es.json.txt)

**Comment by Pathoschild** [comment]
@PlussRolf Thanks a lot! I added that to the next Lookup Anything release.

**Comment by Pathoschild** [comment]
Lookup Anything updated with new translations; closed in favor of #21.
