### ISSUE TITLE
Working Fireplace 1.5.1

### ISSUE THREAD

**Issue by jahangmar** [StardewModders/mod-translations#17]
**[Working Fireplace](https://www.nexusmods.com/stardewvalley/mods/3654)** gives the fireplace a use by forcing the player to light it up when it is cold outside.

## Requested translations
See [default text](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[Chinese](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace/i18n/zh.json)~ (added thanks to @Redlnn!)
- [x] ~[French](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace/i18n/fr.json)~ ([added](https://github.com/jahangmar/StardewValleyMods/pull/11) thanks to @mael-belval!)
- [x] ~[Hungarian](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace/i18n/hu.json)~ ([added](https://github.com/jahangmar/StardewValleyMods/pull/12) thanks to @Annosz!)
- [x] ~[Italian](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace/i18n/it.json)~ ([added](https://github.com/jahangmar/StardewValleyMods/pull/6) thanks to @xLPMG!)
- [x] ~[Japanese](https://github.com/jahangmar/StardewValleyMods/blob/master/WorkingFireplace_Project/WorkingFireplace/i18n/ja.json)~ ([added](https://github.com/jahangmar/StardewValleyMods/pull/7) thanks to @pomepome!)
- [x] ~[Korean](https://github.com/jahangmar/StardewValleyMods/blob/master/WorkingFireplace_Project/WorkingFireplace/i18n/ko.json)~ ([added](https://github.com/jahangmar/StardewValleyMods/pull/8) thanks to @overwritten!)
- [x] ~[Portuguese](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace/i18n/pt.json)~ ([added](https://github.com/jahangmar/StardewValleyMods/commit/c4f6c34f7ad4936dd7aa60424fba581b58292b6c) thanks to @BeckySie!)
- [x] ~[Spanish](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace/i18n/es.json)~ ([added](https://github.com/jahangmar/StardewValleyMods/pull/5) thanks to @xLPMG!)
- [x] ~[Turkish](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace/i18n/tr.json)~ (added thanks to @BURAKMESE!)

## Where translations appear in-game
* `msg.warm` `msg.cold` `msg.spousecold` appear at the start of the day.
* `dia.*` are comments made by your spouse when the fireplace wasn't lit.
* `msg.nowood` is a message displayed when the player tries to click the fireplace without the right amount of wood in their hands.
* `msg.temp*` are displayed when the player enters the bed.

## Credit
Credit for translators is provided in the change log and description on the nexus page.

## See also
* [source code](https://github.com/jahangmar/StardewValleyMods/tree/master/WorkingFireplace_Project/WorkingFireplace)

**Comment by kukuley** [comment]
Chinese | kukuley | [zh.json](https://drive.google.com/file/d/15Q6NGYUzJwFfOiVlfwAvu8IuQffPXqCM/view?usp=sharing)

**Comment by jahangmar** [comment]
@kukuley Thank you again. You commented on the wrong issue (this is a translation for #18) but I added it at the right place.

**Comment by jahangmar** [comment]
Italian and Spanish translations are done.

**Comment by Pathoschild** [comment]
@jahangmar Updated. I also added you to the modder team, so you should be able to edit labels now.

**Comment by BeckySie** [comment]
Portuguese Translation [here](https://drive.google.com/open?id=199wYvwRGCuKx8VvgIPKFmNxCb_9SFb1I) ~

**Comment by jahangmar** [comment]
@BeckySie Thank you very much.

**Comment by Redlnn** [comment]
Chinese translation:
```
{
    "msg.warm": "火焰带来的温度使夜晚变得温暖。",
    "msg.cold": "夜晚的寒冷耗尽了您的能量。",
    "msg.spousecold": "您的家庭在夜间结冰了。",
    "dia.spousecold": "今晚我结冰了。",
    "dia.spousecold_child": "{{child1}} 正在结冰。",
    "dia.spousecold_children": "{{child1}} 和 {{child2}} 正在结冰。",
    "dia.please": "请点燃壁炉。",
    "msg.nowood": "您需要 {{wood_pieces}} 块木头来点火。",
    "msg.temp": "温度: ",
    "msg.tempwarm": "温暖",
    "msg.tempcold": "寒冷"
}
```

**Comment by jahangmar** [comment]
@Redlnn Thank you. It's added to the next release.

**Comment by S-zombie** [comment]
Hi, can I add a better Italian translation? I don't mean to be picky or ungrateful, but the one you have now doesn't seem to have been made by someone fluent in Italian, weird phrasing and straight up wrong words. I apologize to everyone I offended, but my version is more understandable.

> 
{
    "msg.warm": "Il fuoco del camino ti ha tenuto al caldo questa notte.",
    "msg.cold": "Il freddo ha prosciugato le tue energie durante la notte.",
    "msg.spousecold": "La tua famiglia stava congelando stanotte.",
    "dia.spousecold": "Morivo dal freddo stanotte.",
    "dia.spousecold_child": "{{child1}} sta congelando.",
    "dia.spousecold_children": "{{child1}} e {{child2}} stanno congelando.",
    "dia.please": "Accendi il camino, per favore.",
    "msg.nowood": "Hai bisogno di {{wood_pieces}} pezzi di legno per accendere il fuoco.",
    "msg.temp": "Temperatura: ",
    "msg.tempwarm": "caldo",
    "msg.tempcold": "freddo"
}

>

**Comment by S-zombie** [comment]
Hi, can I add a better Italian translation? I don't mean to be picky or ungrateful, but the one you have now doesn't seem to have been made by someone fluent in Italian, weird phrasing and straight up wrong words. I apologize to everyone I offended, but my version is more understandable.

> ```
>{
>    "msg.warm": "Il fuoco del camino ti ha tenuto al caldo questa notte.",
>    "msg.cold": "Il freddo ha prosciugato le tue energie durante la notte.",
>    "msg.spousecold": "La tua famiglia stava congelando stanotte.",
>    "dia.spousecold": "Morivo dal freddo stanotte.",
>    "dia.spousecold_child": "{{child1}} sta congelando.",
>    "dia.spousecold_children": "{{child1}} e {{child2}} stanno congelando.",
>    "dia.please": "Accendi il camino, per favore.",
>    "msg.nowood": "Hai bisogno di {{wood_pieces}} pezzi di legno per accendere il fuoco.",
>    "msg.temp": "Temperatura: ",
>    "msg.tempwarm": "caldo",
>    "msg.tempcold": "freddo"
>}
> ```

**Comment by jahangmar** [comment]
@S-zombie Thank you. I will add this with the next update.

**Comment by Annosz** [comment]
I created a [pull request](https://github.com/jahangmar/StardewValleyMods/pull/12) with the Hungarian translations.

**Comment by Pathoschild** [comment]
@jahangmar You have a few pending translations in pull requests. :)

**Comment by jahangmar** [comment]
Thank you @Annosz and @mael-belval and @overwritten for the translations (and pathoschild for everything).

**Comment by BURAKMESE** [comment]
turkısh
{
   "msg.warm": "Şömine ateşi bu gece seni sıcak tuttu.",
   "msg.cold": "Soğuk bir gecede enerjilerinizi tüketti.",
   "msg.spousecold": "Ailen bu gece donuyordu.",
   "dia.spousecold": "Bu gece soğuktan ölüyordum.",
   "dia.spousecold_child": "{{child1}} donuyor.",
   "dia.spousecold_children": "{{child1}} ve {{child2}} donuyorlar.",
   "dia.please": "Şömineyi aç lütfen.",
   "msg.nowood": "Gerek {{wood_pieces}} ateş yakmak için odun parçaları.",
   "msg.temp": "sıcaklık: ",
   "msg.tempwarm": "sıcak",
   "msg.tempcold": "soğuk"
}

**Comment by Pathoschild** [comment]
@jahangmar You have a pending translation above.

**Comment by jahangmar** [comment]
@BURAKMESE I added your translation and I will release a new version of the mod soon. Thank you.
