### ISSUE TITLE
SMAPI 3.0

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#19]
**[SMAPI](https://smapi.io/)** is the mod loader for Stardew Valley.

## Requested translations
See [default text](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[Chinese](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/zh.json)~ (added thanks to @feathershine!)
- [x] ~[French](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/fr.json)~ (added thanks to @kchapelier!)
- [x] ~[Hungarian](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/hu.json)~ (added thanks to @Annosz!)
- [x] ~[Italian](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/it.json)~ (added thanks to @xCarloC!)
- [x] ~[Japanese](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/ja.json)~ (added thanks to @shirutan!)
- [ ] Korean (missing)
- [x] ~[Portuguese](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/ru.json)~ (added thanks to @L30Bola!)
- [x] ~[Russian](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/ru.json)~ (added thanks to @Osiris901!)
- [x] ~[Spanish](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/es.json)~ (added thanks to @PlussRolf!)
- [x] ~[Turkish](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/i18n/tr.json)~ (added thanks to @berkayylmao!)

## Where translations appear in-game
When invalid content is removed from the save file (e.g. an NPC which no longer exists), a message is shown in the bottom-left corner of the screen after loading the save:
> ![example](https://user-images.githubusercontent.com/230581/68073310-ff1a9580-fd64-11e9-9c93-c1155b4a0cae.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/SMAPI)

**Comment by PlussRolf** [comment]
Spanish - The literal translation has changed a bit, the meaning its the same.
I don't think we have a good word for Crash tbh.

```
{
    "warn.invalid-content-removed": "Se ha quitado contenido inválido para evitar un cierre forzoso (revisa la consola de SMAPI para más información)."
}
```

**Comment by Pathoschild** [comment]
@PlussRolf Thanks! Added in the upcoming SMAPI 3.0.2.

**Comment by shirutan** [comment]
japanese.
```
{
    "warn.invalid-content-removed": "クラッシュを防ぐために無効なコンテンツを取り除きました （詳細はSMAPIコンソールを参照）"
}
```

**Comment by Pathoschild** [comment]
Thanks! Added to the upcoming SMAPI 3.1 update.

**Comment by kchapelier** [comment]
I created a [PR](https://github.com/Pathoschild/SMAPI/pull/689) with the French translation.
Let me know if anything is amiss.

**Comment by Pathoschild** [comment]
Thanks! Added to the next SMAPI release.

**Comment by xCarloC** [comment]
Hi, this is the italian translation:
```
{
    "warn.invalid-content-removed": "Contenuto non valido rimosso per prevenire un crash (Guarda la console di SMAPI per maggiori informazioni)."
}
```

**Comment by Pathoschild** [comment]
Thanks for the help! Added in the upcoming SMAPI 3.3 update.

**Comment by Annosz** [comment]
I added a [pull request](https://github.com/Pathoschild/SMAPI/pull/701) for the Hungarian translation.

**Comment by Pathoschild** [comment]
@Annosz Thanks! It'll be in the upcoming SMAPI 3.4.

**Comment by Pathoschild** [comment]
I derived the last translations based on the wiki and Google Translate. Contributions are always welcome to improve translations, but I'll mark this ticket done.
