### ISSUE TITLE
Lookup Anything 1.23.1

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#21]
**[Lookup Anything](https://www.nexusmods.com/stardewvalley/mods/541)** shows live info about whatever's under your cursor when you press F1. Learn a villager's favourite gifts, when a crop will be ready to harvest, how long a fence will last, why your farm animals are unhappy, and more. 

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [ ] [Chinese](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/zh.json) (incomplete; see lines marked `// TODO`)
- [ ] [French](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/fr.json) (incomplete; see lines marked `// TODO`)
- [ ] [German](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/de.json) (incomplete; see lines marked `// TODO`)
- [ ] Hungarian (missing)
- [ ] [Japanese](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ja.json) (incomplete; see lines marked `// TODO`)
- [ ] [Korean](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ko.json) (incomplete; see lines marked `// TODO`)
- [x] ~[Portuguese](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/pt.json)~ (updated thanks to @L30Bola!)
- [ ] [Russian](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ru.json) (incomplete; see lines marked `// TODO`)
- [ ] Turkish (missing)

## Where translations appear in-game
See [the readme](https://github.com/Pathoschild/StardewMods/tree/develop/LookupAnything#showcase) for examples showing where the translations appear. For example:

* `item.*` appear when you lookup items:  
  > ![common mushroom](https://user-images.githubusercontent.com/230581/50718635-aa808e00-105f-11e9-9c9c-87372c1b3fc9.png)

* `building.*` and `type.building` appear when you lookup different buildings:  
  > ![barn](https://user-images.githubusercontent.com/230581/50718529-8bcdc780-105e-11e9-9aae-e44fe5ea3573.png)  

* `friendship-status.*` is shown when you lookup an NPC:  
  > ![](https://user-images.githubusercontent.com/230581/50718706-5f1aaf80-1060-11e9-8b35-90e9b9d4c85f.png)

* `player.*` appear when you lookup yourself, either from the load screen or in-game:  
  > ![](https://user-images.githubusercontent.com/230581/50718664-fc291880-105f-11e9-8c64-c1218bb7bb8b.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/LookupAnything)

**Comment by jahangmar** [comment]
During the testing of [my german translation](https://github.com/Pathoschild/StardewMods/pull/488) I found the following:
While looking up the pet, the type of the pet is not translated. It shows 
> pet name. Cat

**Comment by Pathoschild** [comment]
@jahangmar Thanks! The next version will use the game's translation from the adoption event, so it won't need a new translation:
> ![](https://user-images.githubusercontent.com/230581/71300976-ffe4a680-2367-11ea-814a-63883b6dc33c.png)

**Comment by L30Bola** [comment]
I'm in doubt on how I should translate the `"friendship-status.kicked-out"`. On which occasions this `friendship-status` happen?

EDIT: Nvm, I just read about it. It happens when you asks Krobus to leave your farmhouse. You can ask him to live with you, as a housemate and, as you can do with the spouses, you can "divorce" him, which is asking him to leave.

**Comment by Pathoschild** [comment]
Lookup Anything updated with new translations; closed in favor of #25.
