### ISSUE TITLE
Debug Mode 1.11

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#23]
**[Debug Mode](https://www.nexusmods.com/stardewvalley/mods/679)** lets you press a button to view debug information and unlock the game's built-in debug commands.

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[Chinese](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/zh.json)~ (updated thanks to @Enaium!)
- [x] ~[German](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/de.json)~ (updated thanks to @jahangmar!)
- [x] ~[Hungarian](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/hu.json)~ (added thanks to @Annosz!)
- [x] ~[Korean](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/ko.json)~ (updated thanks to @Hesper!)
- [x] ~[Portuguese](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/pt.json)~ (updated thanks to @L30Bola!)
- [x] ~[Turkish](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/tr.json)~ (added thanks to @PanPan-p!)

## Where translations appear in-game
See [the readme](https://github.com/Pathoschild/StardewMods/tree/develop/DebugMode#use) for more info. For example:

* `label.event-script` appears when viewing a cutscene, and indicates the event command that's being run to show what's on screen:  
  > ![](https://user-images.githubusercontent.com/230581/50718458-c97e2080-105d-11e9-91e1-7a05b5e213d2.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/DebugMode)

**Comment by Annosz** [comment]
I created a [pull request](https://github.com/Pathoschild/StardewMods/pull/533) with the Hungarian transaltions.

**Comment by Pathoschild** [comment]
Thanks for the help! Added to the next Debug Mode update.

**Comment by PanPan-p** [comment]
It was very easy and I translated it without asking, (sorry) Turkish translation 
[tr.zip](https://github.com/StardewModders/mod-translations/files/5507161/tr.zip)

**Comment by Pathoschild** [comment]
@PanPan-p Thanks for the help! Translations are always welcome, no need to ask first. I added them to the upcoming Debug Mode 1.12.3.

**Comment by Pathoschild** [comment]
That's all the translations done for Debug Mode. Thanks so much to all the translators!
