### ISSUE TITLE
Noclip Mode 1.1

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#24]
**[Noclip Mode](https://www.nexusmods.com/stardewvalley/mods/3900)** lets you press a button to walk through anything (even map boundaries).

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[Chinese](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/zh.json)~ (added thanks to @asqwedcxz741!)
- [x] ~[French](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/fr.json)~ (added thanks to @mael-belval!)
- [x] ~[German](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/de.json)~ (added thanks to @GwydionAshe!)
- [x] ~[Hungarian](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/hu.json)~ (added thanks to @Annosz!)
- [x] ~[Japanese](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/ja.json)~ (added thanks to @shirutan!)
- [x] ~[Korean](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/ko.json)~ (added thanks to @Hesper!)
- [x] ~[Portuguese](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/pt.json)~ (added thanks to @L30Bola!)
- [x] ~[Spanish](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/es.json)~ (added thanks to @cosmogone!)
- [x] ~[Turkish](https://github.com/Pathoschild/StardewMods/blob/develop/NoclipMode/i18n/tr.json)~ (added thanks to @BURAKMESE!)

## Where translations appear in-game
The messages are shown in the bottom-left corner when you enable or disable noclip mode:
> ![enabled message](https://user-images.githubusercontent.com/230581/70878625-3e591a80-1f90-11ea-9d73-61ac7446aa20.png)
> ![disabled message](https://user-images.githubusercontent.com/230581/70878637-46b15580-1f90-11ea-9b99-1ccaf032a97d.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/NoclipMode)

**Comment by GwydionAshe** [comment]
For German:

{
    "enabled-message": "Keine Kollisionen aktiviert; drücke nochmal {{button}} zum ausschalten.",
    "disabled-message": "Keine Kollisionen deaktiviert; drücke nochmal {{button}} zum einschalten."
}

**Comment by Pathoschild** [comment]
@GwydionAshe Thanks! Added in the next Noclip Mode update.

**Comment by L30Bola** [comment]
For Portuguese:
```
{
	"enabled-message": "Modo noclip ativado; pressione {{button}} novamente para desligá-lo.",
	"disabled-message": "Modo noclip desativado; pressione {{button}} novamente para ligá-lo."
}
```

**Comment by L30Bola** [comment]
I commented earlier, but instead I'll open PRs for the translations.

**Comment by shirutan** [comment]
japanese.
```
{
    "enabled-message": "noclipモード 有効; もう一度 {{button}} を押してオフにします。",
    "disabled-message": "noclipモード 無効; もう一度 {{button}} を押してオンにします。"
}
```

**Comment by Pathoschild** [comment]
Thanks! Added to the next Noclip Mode update.

**Comment by cosmogone** [comment]
spanish:
`{
    "enabled-message": "Noclip ha sido habilitado; empuja {{button}} otra vez para inhabilitarlo.",
    "disabled-message": "Noclip ha sido inhabilitado; empuja {{button}} otra vez para habilitarlo."
}`

**Comment by Pathoschild** [comment]
Thanks for the help! I added it to the next update.

**Comment by Annosz** [comment]
I added a [pull request](https://github.com/Pathoschild/StardewMods/pull/527) for the Hungarian translation.

**Comment by Pathoschild** [comment]
Thanks again! Added in the upcoming Noclip Mode 1.2.

**Comment by BURAKMESE** [comment]
turkısh
{
    "enabled-message""noclip modu etkin; kapatmak için {{button}} tuşuna tekrar basın",
"disabled-message":"Noclip modu devre dışı; açmak için {{button}} tuşuna tekrar basın"
}

**Comment by Pathoschild** [comment]
Thanks for the help! Added in the upcoming Noclip Mode 1.2.1.

**Comment by Pathoschild** [comment]
All translations complete. Thanks to all the translators!
