### ISSUE TITLE
Stardew Valley Reimagined 1.5.2

### ISSUE THREAD

**Issue by NinoDorgo** [StardewModders/mod-translations#26]
**[Stardew Valley Reimagined](https://www.nexusmods.com/stardewvalley/mods/4119)** redesigns all outdoor maps.﻿ That includes redone mine entrances, a bedroom for the Dwarf, secret woods expanded to be more woodsy and magical + waterfall spa, and much more!

## Requested translations
See ~~default text~~ and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [ ] Chinese (missing)
- [ ] French (missing)
- [ ] German (missing)
- [ ] Hungarian (missing)
- [ ] Italian (missing)
- [ ] Japanese (missing)
- [ ] Korean (missing)
- [ ] Portuguese (missing)
- [ ] Russian (missing)
- [ ] Spanish (missing)
- [ ] Turkish (missing)

## Where translations appear in-game
Works on everything not but most at heart events

## Credit
TODO

## See also
* ~~See also~~

**Comment by Pathoschild** [comment]
@NinoDorgo The mod needs to be [open-source](https://stardewvalleywiki.com/Modding:Open_source) to request translations here. (It's harder to check/provide translations for a closed-source mod, and the mod's copyright gets very murky.) Feel free to reopen the request if you make the mod open-source, or ping me if you have questions!
