### ISSUE TITLE
Chests Anywhere 1.17.4

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#28]
**[Chests Anywhere](https://www.nexusmods.com/stardewvalley/mods/518)** lets you access your chests, fridge, shipping bin, and Junimo huts from anywhere and organise them your way. Transfer items without having to run around, from the comfort of your bed to the deepest mine level.

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[Hungarian](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/hu.json)~ (added thanks to @Annosz!)
- [x] ~[Korean](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/ko.json)~ (thanks to @Hesper!)

## Where translations appear in-game
The mod adds new options to the chest UI:
* After opening a chest, click the top-left dropdown to see default names for chests and machines:
  > ![](https://user-images.githubusercontent.com/230581/54803190-dbc33000-4c44-11e9-8dd7-26537637ee80.png)
* Click the edit icon to view the chest options:
   > ![](https://user-images.githubusercontent.com/230581/54803175-ccdc7d80-4c44-11e9-8ea4-87414ace02b2.png)
   > ![](https://user-images.githubusercontent.com/230581/54803067-59d30700-4c44-11e9-93c1-5462004f1b24.png)

Errors are shown as popup notifications in the bottom-left corner:  
  > ![](https://user-images.githubusercontent.com/230581/50676019-d8ae9100-0fbf-11e9-8dc8-d8b36673ccb8.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/ChestsAnywhere)

**Comment by Annosz** [comment]
I added a [pull request](https://github.com/Pathoschild/StardewMods/pull/527) for the Hungarian translation.

**Comment by Pathoschild** [comment]
Thanks again! Added in the upcoming Chests Anywhere 1.18.

**Comment by Pathoschild** [comment]
All translations complete. Thanks to all the translators! ❤️
