### ISSUE TITLE
Debug Mode 1.9.5

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#3]
**[Debug Mode](https://www.nexusmods.com/stardewvalley/mods/679)** lets you press a button to view debug information and unlock the game's built-in debug commands.

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/default.json) and [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

language | translations | status
-------- | ------------ | ------
~~French~~ | ~~[fr.json](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/fr.json)~~ | [added](https://github.com/Pathoschild/StardewMods/pull/374) (thanks to @VincentRoth!)
Hungarian | | missing
~~Italian~~ | ~~[it.json](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/it.json)~~ | [added](https://github.com/Pathoschild/StardewMods/pull/440) (thanks to @xLPMG!)
~~Korean~~ | ~~[ko.json](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/ko.json)~~ | [added](https://github.com/Pathoschild/StardewMods/pull/380) (thanks to @S2SKY!)
~~Russian~~ | ~~[ru.json](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/ru.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/394) (thanks to @TheOzonO3!)
Turkish | | missing

See [the readme](https://github.com/Pathoschild/StardewMods/tree/develop/DebugMode#use) for examples showing where the translations appear. For example:

* `label.event-script` appears when viewing a cutscene, and indicates the event command that's being run to show what's on screen:  
  > ![](https://user-images.githubusercontent.com/230581/50718458-c97e2080-105d-11e9-91e1-7a05b5e213d2.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/DebugMode)

**Comment by PlussRolf** [comment]
Don't know if needed but heres goes spanish translation

```
{
    // labels shown on the debug screen
    "label.tile": "tile",
    "label.map": "mapa",
    "label.menu": "menú",
    "label.submenu": "submenú",
    "label.minigame": "minijuego",
    "label.festival-name": "festival",
    "label.event-id": "ID de evento",
    "label.event-script": "guión del evento",
    "label.song": "canción"
}
```

**Comment by Pathoschild** [comment]
@PlussRolf Thanks! Here are the current translations:
```js
{
    // labels shown on the debug screen
    "label.tile": "casilla",
    "label.map": "mapa",
    "label.menu": "menu",
    "label.submenu": "submenu",
    "label.minigame": "minijuego",
    "label.festival-name": "festival",
    "label.event-id": "evento ID",
    "label.event-script": "evento script",
    "label.song": "song" // TODO
}
```
Which version do you prefer (ignoring the `// TODO` line)?

**Comment by Pathoschild** [comment]
Debug Mode was updated with new translations; closed in favor of #23. (@PlussRolf: feel free to reply here anyway!)

**Comment by PlussRolf** [comment]
@Pathoschild 
```
{
    // labels shown on the debug screen
    "label.tile": "casilla", //Didn't think of this one lol. It's the correct translation.
    "label.map": "mapa",
    "label.menu": "menú",
    "label.submenu": "submenú",
    "label.minigame": "minijuego",
    "label.festival-name": "festival",
    "label.event-id": "ID de evento", 
    "label.event-script": "guión del evento", //Makes more sense for me. Thoug i got no issues understanding the previous one
    "label.song": "canción"
}
```

**Comment by Pathoschild** [comment]
@PlussRolf Thanks again! I added those to the next update.
