### ISSUE TITLE
Stardew Valley Expanded v1.10.8

### ISSUE THREAD

**Issue by martin66789** [StardewModders/mod-translations#30]
Stardew Valley Expanded is a fanmade expansion for ConcernedApe's Stardew Valley. This mod features 23 new locations, 126 new character events, 9 new NPCs, a new village, 750 location messages, reimagined maps and festivals (all maps), a huge remastered farm map, a new world map reflecting all changes, and many miscellaneous additions! 

These translations are requested:
- [ ] Hungarian (missing)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://www.nexusmods.com/stardewvalley/mods/3753?tab=description)

**Comment by Pathoschild** [comment]
@martin66789 Unfortunately you can only request translations for your own mods (since you won't be able to add the translation to the official Stardew Valley Expanded release), and the SVE author doesn't include translations directly in the mod.
