### ISSUE TITLE
Data Layers 1.12.2

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#34]
**[Data Layers](https://www.nexusmods.com/stardewvalley/mods/1691)** overlays the world with visual data like bee/Junimo/scarecrow/sprinkler coverage, hidden paths and warps, and more.

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[German](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/de.json)~ (updated thanks to @norges!)
- [x] ~[Italian](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/it.json)~ (updated thanks to @LeecanIt!)
- [x] ~[Korean](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/ko.json)~ (updated thanks to @zhxxn!)
- [x] ~[Spanish](https://github.com/Pathoschild/StardewMods/blob/develop/DataLayers/i18n/es.json)~ (updated thanks to @elCrimar!)

## Where translations appear in-game
Press `F2` in-game to show the data layer menu, then press `left CTRL` or `right CTRL` to cycle through the available overlays. See [the readme](https://github.com/Pathoschild/StardewMods/tree/develop/DataLayers#use) for an example of each overlay.

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/DataLayers)

**Comment by alva-seal** [comment]
I send the pull request ed3597d for german

**Comment by elCrimar** [comment]
Here is the translation in Spanish ;D

{
    // accessible
    "accessible.name": "Accesible",
    "accessible.clear": "Despejado",
    "accessible.occupied": "Ocupado",
    "accessible.impassable": "Intransitable",
    "accessible.warp": "Warp",

    // buildable
    "buildable.name": "Edificable",
    "buildable.buildable": "Puede Construir aquí",
    "buildable.occupied": "Ocupado",
    "buildable.not-buildable": "No puede Construir aquí",

    // coverage: bee houses
    "bee-houses.name": "Cobertura: Casas de Abejas",
    "bee-houses.range": "Rango de la Flor",

    // coverage: Junimo huts
    "junimo-huts.name": "Cobertura: Chozas Junimo",
    "junimo-huts.can-harvest": "Pueden cosechar",
    "junimo-huts.cannot-harvest": "No pueden cosechar",

    // coverage: scarecrows
    "scarecrows.name": "Cobertura: Espantapájaros",
    "scarecrows.protected": "Protegido",
    "scarecrows.exposed": "Expuesto",

    // coverage: sprinklers
    "sprinklers.name": "Cobertura: Aspersores",
    "sprinklers.covered": "Cubierto",
    "sprinklers.dry-crops": "Cultivos Secos",

    // crops: harvest
    "crop-harvest.name": "Cultivos: Listo para Cosechar",
    "crop-harvest.ready": "Listo",
    "crop-harvest.not-ready": "No Listo",
    "crop-harvest.not-enough-time": "Sin Tiempo Suficiente",

    // crops: watered
    "crop-water.name": "Cultivos: Regado",
    "crop-water.watered": "Cultivo Regado",
    "crop-water.dry": "Cultivos Seco",

    // crops: water for paddy crops
    "crop-paddy-water.name": "Cultivos: Agua para Cultivos de Arroz",
    "crop-paddy-water.in-range": "Cerca del Agua",
    "crop-paddy-water.not-in-range": "Tierra Seca",

    // crops: fertilized
    "crop-fertilizer.name": "Cultivos: Fertilizados",
    "crop-fertilizer.fertilizer": "Fertilizado",
    "crop-fertilizer.retaining-soil": "Reteniendo Suelo",
    "crop-fertilizer.speed-gro": "Creciendo con Velocidad",

    // machine processing
    "machines.name": "Máquinas de Procesamiento",
    "machines.empty": "Vacío",
    "machines.processing": "Procesando",
    "machines.finished": "Finalizado",

    // tile grid
    "grid.name": "Cuadrícula de Baldosas",

    // tillable
    "tillable.name": "Cultivable",
    "tillable.tillable": "Cultivable",
    "tillable.tilled": "Cultivado",
    "tillable.occupied": "Ocupado",
    "tillable.not-tillable": "No Cultivable"
}

**Comment by Pathoschild** [comment]
Thanks for the help! Added to the upcoming Data Layers 1.13.2.

**Comment by Pathoschild** [comment]
Translations complete. Thanks to all the translators! 🎊
