### ISSUE TITLE
Ridgeside Village

### ISSUE THREAD

**Issue by PhilBess** [StardewModders/mod-translations#36]
**NOTE: Replace all example links and text. First line of languages table is how it looks when it's completed.**

**[Mod Name](http://example.com/mod)** [mod description here]

## Requested translations
See [default text](https://github.com/Me/Mod/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] Chinese (missing)
- [x] French (missing)
- [x] German (missing)
- [x] Hungarian (missing)
- [x] Italian (missing)
- [x] Japanese (missing)
- [x] Korean (missing)
- [x] Portuguese (missing)
- [x] Russian (missing)
- [x] Spanish (missing)
- [x] Turkish (missing)

## Where translations appear in-game
**TODO**: a brief summary of where translations appear, optionally with screenshots to provide context.

## Credit
**TODO**: do you credit translators in release notes, or somewhere else? Specify here!

## See also
* [source code](https://github.com/Me/Mod)

**Comment by Pathoschild** [comment]
Hi! I'll close this ticket since it doesn't seem to have any info and you don't have any GitHub repos, but feel free to submit a new one for a specific mod you own if needed.
