### ISSUE TITLE
Xtardew Valley

### ISSUE THREAD

**Issue by Codeteus** [StardewModders/mod-translations#37]
**NOTE: Replace all example links and text. First line of languages table is how it looks when it's completed.**

**[Xtardew Valley](https://www.nexusmods.com/stardewvalley/mods/4399?tab=description)** [mod description here]

## Requested translations
See [default text](https://github.com/Me/Mod/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [ ] Chinese (missing)
- [ ] French (missing)
- [ ] German (missing)
- [ ] Hungarian (missing)
- [ ] Italian (missing)
- [ ] Japanese (missing)
- [ ] Korean (missing)
- [ ] Portuguese (missing)
- [ ] Russian (missing)
- [ ] Spanish (missing)
- [ ] Turkish (missing)

## Where translations appear in-game
**TODO**: a brief summary of where translations appear, optionally with screenshots to provide context.

## Credit
**TODO**: do you credit translators in release notes, or somewhere else? Specify here!

## See also
* [source code](https://github.com/Me/Mod)

**Comment by Pathoschild** [comment]
@Codeteus The mod needs to be [open-source](https://stardewvalleywiki.com/Modding:Open_source) to be listed here. Can you link to the repository for the mod?
