### ISSUE TITLE
Lookup Anything 1.21

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#4]
**[Lookup Anything 1.21](https://www.nexusmods.com/stardewvalley/mods/541)** shows live info about whatever's under your cursor when you press F1. Learn a villager's favourite gifts, when a crop will be ready to harvest, how long a fence will last, why your farm animals are unhappy, and more. 

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/default.json) and [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

language | translations | status
-------- | ------------ | ------
~~Chinese~~ | ~~[zh.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/zh.json)~~ | updated (thanks to @binxhlin!)
~~French~~ | ~~[fr.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/fr.json)~~ | [added](https://github.com/Pathoschild/StardewMods/pull/374) (thanks to @VincentRoth!)
~~German~~ | ~~[de.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/de.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/359) (thanks to @Nanogamer7!)
Hungarian | | missing
Italian | | missing
Japanese | [ja.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ja.json) | incomplete (see lines marked `// TODO`)
~~Korean~~ | ~~[ko.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ko.json)~~ | [added](https://github.com/Pathoschild/StardewMods/pull/378) (thanks to @S2SKY!)
Portuguese | [pt.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/pt.json) | incomplete (see lines marked `// TODO`)
~~Russian~~ | ~~[ru.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/ru.json)~~ | [updated](https://github.com/Pathoschild/StardewMods/pull/397) (thanks to @TheOzonO3!)
Spanish | [es.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/es.json) | incomplete (see lines marked `// TODO`)
Turkish | | missing

See [the readme](https://github.com/Pathoschild/StardewMods/tree/develop/LookupAnything#showcase) for examples showing where the translations appear. For example:

* `item.*` appear when you lookup items:  
  > ![keg](https://user-images.githubusercontent.com/230581/50718627-95a3fa80-105f-11e9-9ca9-96de144dd1ad.png)  
  > ![common mushroom](https://user-images.githubusercontent.com/230581/50718635-aa808e00-105f-11e9-9c9c-87372c1b3fc9.png)

* `building.*` and `type.building` appear when you lookup different buildings:  
  > ![barn](https://user-images.githubusercontent.com/230581/50718529-8bcdc780-105e-11e9-9aae-e44fe5ea3573.png)  
  > ![coop](https://user-images.githubusercontent.com/230581/50718534-9b4d1080-105e-11e9-8323-45d435e6ab57.png)  
  > ![slime hutch](https://user-images.githubusercontent.com/230581/50718536-abfd8680-105e-11e9-8041-7a4312eeb404.png)  
  > ![cabin](https://user-images.githubusercontent.com/230581/50718545-c7689180-105e-11e9-87f6-805e8d4801fb.png)  
  > ![mill](https://user-images.githubusercontent.com/230581/50718566-f4b53f80-105e-11e9-8b7f-9098363ef8ca.png)  
  > ![silo](https://user-images.githubusercontent.com/230581/50718549-d4858080-105e-11e9-8fbd-80e008b28aea.png)  
  > ![stable](https://user-images.githubusercontent.com/230581/50718575-1d3d3980-105f-11e9-9d9c-c6464b2d9d36.png)

* `friendship-status.*` is shown when you lookup an NPC:  
  > ![](https://user-images.githubusercontent.com/230581/50718706-5f1aaf80-1060-11e9-8b35-90e9b9d4c85f.png)

* `player.*` appear when you lookup yourself, either from the load screen or in-game:  
  > ![](https://user-images.githubusercontent.com/230581/50718664-fc291880-105f-11e9-8c64-c1218bb7bb8b.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/LookupAnything)

**Comment by binxhlin** [comment]
Hello
I update your "zh.json" file and you just rename ".txt" to ".json"
[zh.txt](https://github.com/StardewModders/mod-translations/files/3046335/zh.txt)

**Comment by Pathoschild** [comment]
Thanks a lot! I added your translations.

You translated `player.farm-map.custom` as 传统, which Google translates to "Traditional". The intended meaning is "a new map that is not part of the normal game" (i.e. custom-made). Let me know if a different translation for that one would be better!

**Comment by binxhlin** [comment]
Well,it is my fault.I change the right translation.
传统 → 自定义
If any other translation is strange,write a message to me.
Sorry and thanks to you.
It is the new file.↓
[zh.txt](https://github.com/StardewModders/mod-translations/files/3051086/zh.txt)

**Comment by Pathoschild** [comment]
Thanks!

**Comment by Pathoschild** [comment]
Superseded by #15.
