### ISSUE TITLE
Harvey Big Dialogue

### ISSUE THREAD

**Issue by Mylpe** [StardewModders/mod-translations#43]
**[Harvey Big Dialogue](http:///stardewvalley/mods/8403)** New phrases for Harvey, new dialogues everyday, more conversations... 
(Opinion note: Let's face it, Harvey is very annoying! I need this mod in my language! Thankful)
## Requested translations
See [default text](https://github.com/Me/Mod/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

For a missing translation:
   - [x] Chinese (missing)
   - [x] Portuguese
   - [x] Japanese
   - [x] Russian
   - [x] Espanol
   And more... :(
## Credit
 #43

**Comment by Pathoschild** [comment]
Hi! I closed this request because it seems incomplete; the default text link is broken, and mods need to be [open-source](https://stardewvalleywiki.com/Modding:Open_source) to be listed here. Feel free to submit a new corrected post if needed!
