### ISSUE TITLE
Stardew Valley Expanded

### ISSUE THREAD

**Issue by Dramn** [StardewModders/mod-translations#44]
**NOTE: Replace all example links and text. First line of languages table is how it looks when it's completed.**

**[STARDEW VALLEY EXPANDED](https://www.nexusmods.com/stardewvalley/mods/3753)** [https://www.nexusmods.com/stardewvalley/mods/3753]

## Requested translations
See [default text](https://github.com/Me/Mod/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [ ] Hungarian (missing)
- [ ] Italian (missing)
- [ ] Turkish (missing)

## Where translations appear in-game
**TODO**: a brief summary of where translations appear, optionally with screenshots to provide context.

## Credit
**TODO**: do you credit translators in release notes, or somewhere else? Specify here!

## See also
* [source code](https://github.com/Me/Mod)

**Comment by Pathoschild** [comment]
Hi! I closed this request because it seems incomplete; the default text link is broken, that mod doesn't support translations, and you're not the mod's author.
