### ISSUE TITLE
Buxom Caroline Character and Dialogue Overhaul - Can Date and Marry

### ISSUE THREAD

**Issue by alpaquita** [StardewModders/mod-translations#46]
**NOTE: Replace all example links and text. First line of languages table is how it looks when it's completed.**

**[Buxom Caroline Character and Dialogue Overhaul - Can Date and Marry](https://www.nexusmods.com/stardewvalley/mods/3820?tab=description)** [you can marry caroline, there are events and new sprites, sprites do not matter, they can be removed, but seriously, I want to marry caroline]

## Requested translations
 These translations are requested:

-->

- [ ] Spanish (missing)

**Comment by Pathoschild** [comment]
@alpaquita Hi! Unfortunately only [open-source mods](https://stardewvalleywiki.com/Modding:Open_source) are listed in the repo. Feel free to reopen this if you post the mod code on a site like GitHub with an open-source license though.
