### ISSUE TITLE
Shoplifter 1.1.3

### ISSUE THREAD

**Issue by TheMightyAmondee** [StardewModders/mod-translations#48]
[Shoplifter](https://www.nexusmods.com/stardewvalley/mods/8569) is a mod that adds the ability to steal items from certain vanilla shops when the shopkeeper isn't present. Penalties will apply for getting caught shoplifting, so make sure no one is around first!

## Requested translations
See [default text](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[Chinese](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/zh.json)~ (added thanks to 20080618!)
- [x] ~[French](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/fr.json)~ (added thanks to @Breeis!)
- [x] ~[German](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/de.json)~ (added thanks to @NotErikWasTaken!)
- [ ] Hungarian (missing)
- [x] ~[Italian](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/it.json)~ (added thanks to @peanutbatteries!)
- [ ] Japanese (missing)
- [x] ~[Korean](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/ko.json)~ (added thanks to Aromay7!)
- [x] ~[Portuguese](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/pt.json)~ (added thanks to @Kadomine!)
- [X] ~[Russian](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/ru.json)~ (added thanks to @Bellden!)
- [x] ~[Spanish](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/es.json)~ (added thanks to @viridian-fog!)
- [x] ~[Turkish](https://github.com/TheMightyAmondee/Shoplifter/blob/master/Shoplifter/i18n/tr.json)~ (added thanks to @zenura!)

Note: The translations requested include tokens. Make sure anything contained within the double curly braces remain the same as the ``default.json``. For more information regarding tokens please see the [translation guide](https://stardewvalleywiki.com/Modding:Translations).

## Where translations appear in-game
Translations appear in game after getting caught by an npc and when the player is given the option to shoplift.

## Credit
Full credit given to translators in the release notes and on the mod page. Thanks for contributing!

## See also
* [source code](https://github.com/TheMightyAmondee/Shoplifter/tree/master/Shoplifter)

**Comment by peanutbatteries** [comment]
Hiya, I translated this into italian
[it.zip](https://github.com/StardewModders/mod-translations/files/7845944/it.zip)

**Comment by TheMightyAmondee** [comment]
Thanks @peanutbatteries! I've just added the translation files to the mod page.

**Comment by Breeis** [comment]
I like your mod. It adds an RPG side to the game.
So I translated it into French
[fr.zip](https://github.com/StardewModders/mod-translations/files/7963669/fr.zip)

**Comment by Kadomine** [comment]
hi, i made a portuguese translation for your mod. hope it helps! <3
[pt.zip](https://github.com/StardewModders/mod-translations/files/7964780/Shoplifter.PT-BR.translation.zip)

**Comment by TheMightyAmondee** [comment]
Thank you @Breeis and @Kadomine! Translation files have now been added to the mod page.

**Comment by NotErikWasTaken** [comment]
A bit late to the party, but here is a german translation.
[de.zip](https://github.com/StardewModders/mod-translations/files/8004655/de.zip)

**Comment by TheMightyAmondee** [comment]
Thanks @NotErikWasTaken! I've just released a new mod version with all current translations. Thank you for contributing!

**Comment by viridian-fog** [comment]
I'm a bit late to this but here's the spanish translation ^^
[es.zip](https://github.com/StardewModders/mod-translations/files/9040874/es.zip)

**Comment by TheMightyAmondee** [comment]
Just added the spanish translation. Thank you @viridian-fog!

**Comment by zenura** [comment]
[tr.zip](https://github.com/StardewModders/mod-translations/files/9079235/tr.zip)
turkish

**Comment by TheMightyAmondee** [comment]
Thank you @zenura! Turkish translation has now been added.

**Comment by Bellden** [comment]
Hi, i've left the request of adding russian file, it's done

**Comment by TheMightyAmondee** [comment]
Thanks @Bellden, I've gone ahead and added the russian translation!

**Comment by TheMightyAmondee** [comment]
Closed in favour of #59 for the new version of Shoplifter. Thank you to all the translators!
