### ISSUE TITLE
Stardew News Feed 1.8

### ISSUE THREAD

**Issue by Mikesnorth** [StardewModders/mod-translations#5]
**[Stardew News Feed](https://www.nexusmods.com/stardewvalley/mods/3206)** inspects various locations every morning and provides notifications when harvestable items are found. It now also notifies the player of nearby NPC's with birthdays.

## Requested translations
See [default text](https://github.com/Mikesnorth/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/default.json) and [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

language | translations | status
-------- | ------------ | ------
~~Chinese~~ | ~~[zh.json](https://github.com/OtherBuckets/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/zh.json)~~ | added (thanks to @binxhlin!)
~~French~~ | ~~[fr.json](https://github.com/Mikesnorth/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/fr.json)~~ | [added](https://github.com/OtherBuckets/StardewNewsFeed/pull/28) (thanks to @VincentRoth!)
German | [de.json](https://github.com/Mikesnorth/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/de.json) | needs proofreading
Hungarian | | missing
~~Italian~~ | ~~[it.json](https://github.com/Mikesnorth/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/it.json)~~ | [added](https://github.com/OtherBuckets/StardewNewsFeed/pull/31) (thanks to @sfal!)
Japanese | | missing
~~Korean~~ | ~~[ko.json](https://github.com/OtherBuckets/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/ko.json)~~ | [added](https://github.com/OtherBuckets/StardewNewsFeed/pull/29) (thanks to @S2SKY!)
~~Portuguese~~ | ~~[pt.json](https://github.com/OtherBuckets/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/pt.json)~~ | [added](https://github.com/OtherBuckets/StardewNewsFeed/pull/30) (thanks to @kelvindules!)
~~Russian~~ | ~~[ru.json](https://github.com/Mikesnorth/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/ru.json)~~ | [added](https://github.com/OtherBuckets/StardewNewsFeed/pull/18) (thanks to @Elka228!)
Spanish | [es.json](https://github.com/Mikesnorth/StardewNewsFeed/blob/master/StardewNewsFeed/i18n/es.json) | needs proofreading
Turkish | | missing

I attempted to add German and Spanish translations myself, but I'm far from fluent in either. If someone wouldn't mind simply checking my current translations for accuracy that would be appreciated.

## Credit
Naturally, full credit for the translator will be added to both the readme in the source code, and in the description on the mod page.

## See also
* [source code](https://github.com/Mikesnorth/StardewNewsFeed)

**Comment by Pathoschild** [comment]
French translations [submitted via pull request](https://github.com/OtherBuckets/StardewNewsFeed/pull/28) by @VincentRoth. Thanks!

**Comment by Pathoschild** [comment]
Hi @Mikesnorth! You've had [an unanswered pull request](https://github.com/OtherBuckets/StardewNewsFeed/pull/31) open for 19 days, but you should respond to messages and pull requests within 72 hours while the request is open here (see [info on the wiki](https://stardewvalleywiki.com/Modding:Translations#Using_translations)). That avoids confusion like duplicate translations being submitted. If you're still looking for translations, could you take a look at the pull request?

**Comment by binxhlin** [comment]
Hello
I create "zh.txt" file and you just rename ".txt" to ".json"
[zh.txt](https://github.com/StardewModders/mod-translations/files/3046433/zh.txt)

**Comment by Pathoschild** [comment]
@Mikesnorth I closed this request due to non-response. I'll add an issue to your repo with @binxhlin's translation above so it's not lost. Feel free to create a new request when you're available to handle translations!
