### ISSUE TITLE
Stardew Valley Expanded v1.14.18 - ITA

### ISSUE THREAD

**Issue by Shevaara** [StardewModders/mod-translations#57]
## [Stardew Valley Expanded](https://www.nexusmods.com/stardewvalley/mods/3753)
Permission granted by [FlashShifter on Reddit ](https://www.reddit.com/r/StardewValleyExpanded/comments/kzxdep/comment/gjqjff0/?utm_source=share&utm_medium=web2x&context=3) for Italian translation

## Requested translations
See [default text](https://github.com/Me/Mod/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

Partial translation:
   - [ ] [Italian](https://github.com/Shevaara/StardewMods/blob/main/SVEv1.14.18-ITA/it.json) (incomplete)

First time on git, open to suggestions about how to improve this post

**Comment by Pathoschild** [comment]
@Shevaara Hi! This repository is for the original mod authors to request translations which they'll release as part of their mod, not to request someone upload a new one. So I'll close this ticket, but feel free to ask in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) if you have any questions about translating it.
