### ISSUE TITLE
persian

### ISSUE THREAD

**Issue by vimax65** [StardewModders/mod-translations#60]
**NOTE: Replace all example links and text. First line of languages table is how it looks when it's completed.**

**[Mod Name](http://example.com/mod)** [mod description here]

## Requested translations
See [default text](https://github.com/Me/Mod/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [ ] Chinese (missing)
- [ ] French (missing)
- [ ] German (missing)
- [ ] Hungarian (missing)
- [ ] Italian (missing)
- [ ] Japanese (missing)
- [ ] Korean (missing)
- [ ] Portuguese (missing)
- [ ] Russian (missing)
- [ ] Spanish (missing)
- [ ] Turkish (missing)

## Where translations appear in-game
**TODO**: a brief summary of where translations appear, optionally with screenshots to provide context.

## Credit
**TODO**: do you credit translators in release notes, or somewhere else? Specify here!

## See also
* [source code](https://github.com/Me/Mod)

**Comment by Pathoschild** [comment]
Hi! I'll close this since it doesn't match an existing mod. See [the readme for more info on this repo](https://github.com/StardewModders/mod-translations#readme).
