### ISSUE TITLE
East Scrap Mod translation needed

### ISSUE THREAD

**Issue by ElGremioMaestro** [StardewModders/mod-translations#62]
**NOTE: Replace all example links and text. First line of languages table is how it looks when it's completed.**

**[Mod Name](http://example.com/mod)** [mod description here]

## Requested translations
See [default text](https://github.com/Me/Mod/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [ ] Chinese (missing)
- [ ] French (missing)
- [ ] German (missing)
- [ ] Hungarian (missing)
- [ ] Italian (missing)
- [ ] Japanese (missing)
- [ ] Korean (missing)
- [ ] Portuguese (missing)
- [ ] Russian (missing)
- [ ] Spanish (missing)
- [ ] Turkish (missing)

## Where translations appear in-game
**TODO**: a brief summary of where translations appear, optionally with screenshots to provide context.

## Credit
**TODO**: do you credit translators in release notes, or somewhere else? Specify here!

## See also
* [source code](https://github.com/Me/Mod)

**Comment by theRealDuda** [comment]
Hi! It looks like you forgot to change the example text!
Could you please at least attach the link to the mod repo?
Thanks in advance.

**Comment by Pathoschild** [comment]
Hi! Only the author of each mod can open an issue here, since they'll be the ones adding the contributed translations to the mod. Feel free to ask the mod author about supporting translations though!
