### ISSUE TITLE
CJB Item Spawner 1.11.5

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#7]
**[CJB Item Spawner](https://www.nexusmods.com/stardewvalley/mods/93)** adds an in-game menu to spawn any items you want.

## Requested translations
See [default text](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[French](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/fr.json)~ (added thanks to @VincentRoth!)
- [x] ~[Hungarian](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/hu.json)~ (added thanks to @therealmate!)
- [x] ~[Italian](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/it.json)~ (added thanks to @xLPMG!)
- [x] ~[Japanese](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/ja.json)~ (added thanks to @shirutan!)
- [x] ~[Korean](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/ko.json)~ (added thanks to @S2SKY!)
- [x] ~[Spanish](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/es.json)~ (added thanks to @manuqp!)
- [x] ~[Turkish](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/tr.json)~ (added thanks to @BURAKMESE!)

## Where translations appear in-game
The translations are shown in-game when you press `i` to open the menu.

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/CJBok/SDV-Mods/tree/master/CJBItemSpawner)

**Comment by xCarloC** [comment]
Hi, i start to create italian translation, but I have a issue.
Can I have a screen of this world "tabs.all": "All". Becouse italian has two terms for indicate all.

**Comment by therealmate** [comment]
[hu.txt](https://github.com/StardewModders/mod-translations/files/4307866/hu.txt)

**Comment by Pathoschild** [comment]
Thanks for the help! It'll be in the next CJB Item Spawner update.

**Comment by BURAKMESE** [comment]
#
[hua.txt](https://github.com/StardewModders/mod-translations/files/4410194/hua.txt)




turkısh

**Comment by Pathoschild** [comment]
Thanks for the help! Added in the upcoming CJB Item Spawner 1.12.1.

**Comment by Pathoschild** [comment]
All translations done. Thanks to all the translators!
