### ISSUE TITLE
CJB Show Item Sell Price 1.9.4

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#8]
**[CJB Show Item Sell Price](https://www.nexusmods.com/stardewvalley/mods/5)** shows the sell price of items in your inventory.

## Requested translations
See [default text](https://github.com/CJBok/SDV-Mods/blob/master/CJBShowItemSellPrice/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[French](https://github.com/CJBok/SDV-Mods/blob/develop/CJBShowItemSellPrice/i18n/fr.json)~ (added thanks to @VincentRoth!)
- [x] ~[Hungarian](https://github.com/CJBok/SDV-Mods/blob/develop/CJBShowItemSellPrice/i18n/hu.json)~ (added thanks to @Annosz!)
- [x] ~[Italian](https://github.com/CJBok/SDV-Mods/blob/develop/CJBShowItemSellPrice/i18n/it.json)~ (added thanks to @xCarloC!)
- [x] ~[Japanese](https://github.com/CJBok/SDV-Mods/blob/develop/CJBShowItemSellPrice/i18n/ja.json)~ (added thanks to @shirutan!)
- [x] ~[Korean](https://github.com/CJBok/SDV-Mods/blob/develop/CJBShowItemSellPrice/i18n/ko.json)~ (added thanks to @S2SKY!)
- [x] ~[Turkish](https://github.com/CJBok/SDV-Mods/blob/develop/CJBShowItemSellPrice/i18n/tr.json)~ (added thanks to @BURAKMESE!)

## Where translations appear in-game
The translations are shown when you put the cursor over an item in your inventory or toolbar:
> ![](https://user-images.githubusercontent.com/230581/50748292-a80c6880-1206-11e9-9b57-fd4242ab00be.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/CJBok/SDV-Mods/tree/master/CJBShowItemSellPrice)

**Comment by PlussRolf** [comment]
Don't know if needed but heres goes spanish translation

```
{
    "labels.single-price": "Unidad",
    "labels.stack-price": "Montón"
}
```

**Comment by Pathoschild** [comment]
@PlussRolf Thanks! Here are the existing translations:
```js
{
    "labels.single-price": "Una unidad",
    "labels.stack-price": "Montón"
}
```
Which version do you prefer?

**Comment by PlussRolf** [comment]
hmmm they are essentially the same.
The existing one can be translated to "One Unit" while mine was "Unit".
I would stick with the existing one, as it's a bit more direct and easy to understand.

**Comment by xCarloC** [comment]
Hi, this is the italian translation. I don't kwon how to translate the world stack, becouse we don't have one(We use stack, when speak about programming). Instead I use total.
{
    "labels.single-price": "Valore Singolo",
    "labels.stack-price": "Valore Totale"
}

**Comment by Pathoschild** [comment]
Thanks! Added in the next CJB Show Item Sell Price update.

**Comment by Annosz** [comment]
I created a [pull request](https://github.com/CJBok/SDV-Mods/pull/108) with the Hungarian translations.

**Comment by Pathoschild** [comment]
Thanks for the help! It'll be in the next update.

**Comment by BURAKMESE** [comment]
turkısh 

    "labels.single-price"Birim değeri ",
"labels.stack-price":Toplam değer"
}

**Comment by Pathoschild** [comment]
Thanks for the help! Added in the upcoming CJB Show Item Sell Price 1.9.6.

**Comment by Pathoschild** [comment]
All translations done. Thanks to all the translators!
