### ISSUE TITLE
Tractor Mod 4.9.1

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/mod-translations#9]
**[Tractor Mod](https://www.nexusmods.com/stardewvalley/mods/1401)** lets you buy a tractor to more efficiently work with crops, clear twigs and rocks, etc.

## Requested translations
See [default text](https://github.com/Pathoschild/StardewMods/blob/develop/TractorMod/i18n/default.json) and the [translation guide](https://stardewvalleywiki.com/Modding:Translations). These translations are requested:

- [x] ~[French](https://github.com/Pathoschild/StardewMods/blob/develop/TractorMod/i18n/fr.json)~ (added thanks to @Mysti57!)
- [x] ~[Hungarian](https://github.com/Pathoschild/StardewMods/blob/develop/TractorMod/i18n/hu.json)~ (added thanks to @therealmate!)
- [x] ~[Italian](https://github.com/Pathoschild/StardewMods/blob/develop/TractorMod/i18n/it.json)~ (added thanks to @LeecanIt!)
- [x] ~[Korean](https://github.com/Pathoschild/StardewMods/blob/develop/TractorMod/i18n/ko.json)~ (added thanks to @S2SKY!)
- [x] ~[Turkish](https://github.com/Pathoschild/StardewMods/blob/develop/TractorMod/i18n/tr.json)~ (added thanks to @cilekli-link!)

## Where translations appear in-game
* `garage.name` and `garage.description` are shown when buying a new garage from Robin:  
  > ![image](https://user-images.githubusercontent.com/230581/52752486-fc062c00-2fc0-11e9-9a25-9e874822ebe5.png)
* `buff.name` is the name of the buff shown when riding the tractor:  
  > ![image](https://user-images.githubusercontent.com/230581/52752475-e6910200-2fc0-11e9-9f04-4adec013509d.png)

## Credit
Full credit for translators is provided in the release notes. Thanks!

## See also
* [source code](https://github.com/Pathoschild/StardewMods/tree/develop/TractorMod)

**Comment by cilekli-link** [comment]
[tr.txt](https://github.com/StardewModders/mod-translations/files/3314336/tr.txt)

**Comment by Pathoschild** [comment]
@cilekli-link Thanks for the help! Added in the next Tractor Mod update.

**Comment by PlussRolf** [comment]
Don't know if needed, but here it goes spanish translation.

```
{
    "buff.name": "El poder del tractor",
    "garage.name": "Garage del Tractor ",
    "garage.description": "Un garage para guardar tu tractor. Tractor incluido!"
}
```

**Comment by Pathoschild** [comment]
@PlussRolf Thanks! Here are the existing translations:
```js
{
    "buff.name": "Energía del tractor",
    "garage.name": "Garaje del tractor",
    "garage.description": "Un garaje donde guardar tu tractor. ¡Con tractor incluido!"
}
```
Which version do you prefer?

**Comment by PlussRolf** [comment]
The existing one is better :).
In my translation buff.name is out of context and the garage.description is a bit lacking.

**Comment by therealmate** [comment]
Hungarian:
{
    "buff.name": "Traktor erő ",
    "garage.name": "Traktor garázs",
    "garage.description": "Egy garázs ahol tárolhatod a traktorodat.Traktor is jár hozzá"
}

**Comment by therealmate** [comment]
Hungarian:
[hu.txt](https://github.com/StardewModders/mod-translations/files/4298988/hu.txt)

**Comment by Pathoschild** [comment]
@therealmate Thanks! I added that to upcoming ~Chests Anywhere 1.18~ Tractor Mod 4.10 update.

**Comment by Pathoschild** [comment]
All translations complete. Thanks to all the translators! ❤️

**Comment by therealmate** [comment]
Chests anywhere?

**Comment by Pathoschild** [comment]
Fixed, sorry for the confusion!
